apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comfyui.fullname" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "comfyui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comfyui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "comfyui.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "comfyui.fullname" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: INSTALL_DIR
              value: /home/comfy/install
          {{- if .Values.storage.base.enabled }}
            - name: BASE_DIR
              value: /home/comfy/base
          {{- else }}
            - name: BASE_DIR
              value: ${INSTALL_DIR}/ui
          {{- end }}
          {{- if .Values.storage.temp.enabled }}
            - name: TEMP_DIR
              value: /home/comfy/temp
          {{- else }}
            - name: TEMP_DIR
              value: ${INSTALL_DIR}/ui/temp
          {{- end }}
          {{- if .Values.storage.output.enabled }}
            - name: OUTPUT_DIR
              value: /home/comfy/output
          {{- else }}
            - name: OUTPUT_DIR
              value: ${INSTALL_DIR}/ui/output
          {{- end }}
          {{- if .Values.storage.input.enabled }}
            - name: INPUT_DIR
              value: /home/comfy/input
          {{- else }}
            - name: INPUT_DIR
              value: ${INSTALL_DIR}/ui/input
          {{- end }}
          {{- if .Values.storage.user.enabled }}
            - name: USER_DIR
              value: /home/comfy/user
          {{- else }}
            - name: USER_DIR
              value: ${INSTALL_DIR}/ui/user
          {{- end }}
          {{- if .Values.gpu.enabled }}
            - name: GPU_TYPE
              value: {{ .Values.gpu.type }}
          {{- else }}
            - name: GPU_TYPE
              value: cpu
          {{- end }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          volumeMounts:
          {{- if .Values.storage.install.enabled }}
            - name: install
              mountPath: /home/comfy/install
          {{- end }}
          {{- if .Values.storage.base.enabled }}
            - name: base
              mountPath: /home/comfy/base/
          {{- end }}
          {{- if .Values.storage.temp.enabled }}
            - name: temp
              mountPath: /home/comfy/temp/
          {{- end }}
          {{- if .Values.storage.output.enabled }}
            - name: output
              mountPath: /home/comfy/output/
          {{- end }}
          {{- if .Values.storage.input.enabled }}
            - name: input
              mountPath: /home/comfy/input/
          {{- end }}
          {{- if .Values.storage.user.enabled }}
            - name: user
              mountPath: /home/comfy/user/
          {{- end }}
       {{- if .Values.vpn.enabled }}
        - name: vpn
          image: "ghcr.io/qdm12/gluetun:{{ .Values.gluten.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          env:
            {{- with .Values.gluten.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}            
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DNS_SERVER
              value: "off"
            - name: UPDATER_PERIOD
              value: "24h"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.233.0.0/16"
            - name: TZ
              value: Europe/Riga
            - name: FIREWALL_INPUT_PORTS
              value: "{{ .Values.service.port }}"
            - name: VPN_SERVICE_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vpn.secret }}"
                  key: provider
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vpn.secret }}"
                  key: user
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vpn.secret }}"
                  key: password
            - name: SERVER_COUNTRIES
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vpn.secret }}"
                  key: countries
            - name: PUBLICIP_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vpn.secret }}"
                  key: public_ip_token
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            privileged: true
            capabilities:
              add:
                - SYS_MODULE
                - NET_ADMIN
                - NET_RAW
                - MKNOD
        {{- end }}          
      volumes:
        {{- if .Values.storage.install.enabled }}
        - name: install
          persistentVolumeClaim:
            claimName: install
        {{- end }}
        {{- if .Values.storage.base.enabled }}
        - name: base
          persistentVolumeClaim:
            claimName: base
        {{- end }}
        {{- if .Values.storage.temp.enabled }}
        - name: temp
          persistentVolumeClaim:
            claimName: temp
        {{- end }}
        {{- if .Values.storage.output.enabled }}
        - name: output
          persistentVolumeClaim:
            claimName: output
        {{- end }}
        {{- if .Values.storage.input.enabled }}
        - name: input
          persistentVolumeClaim:
            claimName: input
        {{- end }}
        {{- if .Values.storage.user.enabled }}
        - name: user
          persistentVolumeClaim:
            claimName: user
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
