{{- range $k,$v := .Values.storage }}
{{- if $v.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $k }}
  namespace: {{ $.Release.Namespace }}
{{- with $v.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $v.labels  }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ $v.accessMode | default "ReadWriteOnce"}}
  resources:
    requests:
      storage: {{ $v.size | quote | default "20Gi" }}
  {{- if $v.volumeName }}
  volumeName: {{ $v.volumeName }}
  {{- end }}
  {{- if $v.storageClass }}
  storageClassName: {{ $v.storageClass }}
  {{- end }}
{{- end }}
{{- end }}