name: Image Publish for CI/CD pipelines
on:
  push:
    paths:
      - deploy/**
    tags:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  build-n-publish:
    if: contains(github.ref,'tag')
    name: Build and Release CI/CD Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get latest Runner Version and set repos
        id: versions
        run: |
          echo runner=`curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
          echo container_hooks=`curl --silent "https://api.github.com/repos/actions/runner-container-hooks/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
          echo helmfile=`curl --silent "https://api.github.com/repos/helmfile/helmfile/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
          echo kubectl=`curl -L -s https://dl.k8s.io/release/stable.txt` >> $GITHUB_OUTPUT
          echo helm=`curl --silent "https://api.github.com/repos/helm/helm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'` >> $GITHUB_OUTPUT
          echo gitlab_tofu=`curl -s https://gitlab.com/api/v4/projects/53866919/releases/ | jq '.[]' | jq -r '.name' | head -1` >> $GITHUB_OUTPUT
          echo tfsec=`curl --silent "https://api.github.com/repos/aquasecurity/tfsec/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:          
          tags: |
            type=ref,event=push tag
            type=ref,event=push
          labels: org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all    
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Log in to the Github Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Log in to the Docker Container registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
      - name: Log in to the Gitlab Container registry
        uses: docker/login-action@v4
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_ACCOUNT }}
          password: ${{ secrets.GITLAB_TOKEN }} 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: GitHub

      - name: Login to Amazon ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_PATH }}

      - name: Build and Push images to GitHub
        uses: docker/build-push-action@v7
        with:
          context: deploy
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/deploy:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repostiory_owner }}/deploy:latest
            ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:latest
            ${{ secrets.ECR_REPO_PATH }}/deploy:${{ steps.meta.outputs.tag }}
            ${{ secrets.ECR_REPO_PATH }}/deploy:latest
            ${{ secrets.GITLAB_REGISTRY_PATH }}/deploy:latest
            ${{ secrets.GITLAB_REGISTRY_PATH }}/deploy:${{ steps.meta.outputs.tag }}
          platforms: linux/amd64
          build-args: |
            RUNNER_VERSION=${{ steps.versions.outputs.runner }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ steps.versions.outputs.container_hooks }}
            HELMFILE_VERSION=${{ steps.versions.outputs.helmfile }}
            KUBECTL_VERSION=${{ steps.versions.outputs.kubectl }}
            HELM_VERSION=${{ steps.versions.outputs.helm }}
            GITLAB_TOFU_VERSION=${{ steps.versions.outputs.gitlab_tofu }}
            TFSEC_VERSION=${{ steps.versions.outputs.tfsec }}
          cache-from: type=gha
