name: Test Helm Chart
on:
  pull_request:
    paths:
      - 'charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-helm
  cancel-in-progress: true

jobs:
  changed-charts:
    if: github.event_name == 'pull_request'
    name: Get Changed Files for Testing
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          matrix: true
          path: 'charts'
          
      - name: Debug
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

  test-chart:
    name: Test Chart
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      matrix:
        version:
          - v1.36.1
          - v1.35.5
          - v1.34.8
          - v1.33.12
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
   
    - name: Setup Helm
      uses: azure/setup-helm@v5

    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2
        
    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        ct lint --all
        ct list-changed --target-branch ${{ github.event.repository.default_branch }}
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1
      with:
        version: ${{ matrix.version }}

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        scan-type: 'config'
        format: 'sarif'
        output: 'trivy-results.sarif'
        hide-progress: true
        scanners: 'vuln'
        severity: "MEDIUM,HIGH,CRITICAL"
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: 'trivy-results.sarif'
        category: helm