name: Images for Kubernetes pods
on:
  pull_request:
    paths-ignore:
      - deploy/**
      - charts/**
  push:
    paths-ignore:
      - deploy/**
      - charts/**
  schedule:
    - cron: "0 2 * * 0"

jobs: 
  changed-images:
    if: github.event_name == 'pull_request'
    name: Get Changed Files for Testing
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.changed-files.outputs.all_changed_files }}
      kubectl: ${{ steps.outputs.versions.kubectl }}
      helm: ${{ steps.outputs.versions.helm }}
      codeserver: ${{ steps.outputs.versions.codeserver }}
      ghcli: ${{ steps.outputs.versions.ghcli }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 0
          matrix: true
          files_ignore: |
            charts/**
            deploy/**
            .github/**
            .releaserc

      - name: Get latest Runner Version and set repos
        id: versions
        run: |
          echo kubectl=`curl -L -s https://dl.k8s.io/release/stable.txt` >> $GITHUB_OUTPUT
          echo helm=`curl --silent "https://api.github.com/repos/helm/helm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'` >> $GITHUB_OUTPUT
          echo codeserver=$(curl -s "https://api.github.com/repos/coder/code-server/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT
          echo ghcli=$(curl -s "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT

  test-image:
    name: Build and Test Container Images
    if: github.event_name == 'pull_request'
    needs: changed-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: write
    strategy:
      matrix:
        target: ${{ fromJSON(needs.changed-images.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all    
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
         
      - name: Log in to the Github Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Test Build for ${{ matrix.target }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ inputs.target_dir }}
          push: false
          tags: ghcr.io/manpreetsnehra/${{ matrix.target }}:test
          platforms: linux/amd64
          build-args: |
            KUBECTL_VERSION=${{ steps.versions.outputs.kubectl }}
            HELM_VERSION=${{ steps.versions.outputs.helm }}
            GITLAB_TOFU_VERSION=${{ steps.versions.outputs.gitlab_tofu }}
            TFSEC_VERSION=${{ steps.versions.outputs.tfsec }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-n-publish:
    if: contains(github.ref,'master')
    name: Build and Release Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: write
      id-token: write
    strategy:
      matrix:
        image:
          - codeserver
          - comfyui
          - nginx
          - whisparr
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get latest Runner Version and set repos
        id: versions
        run: |
          echo kubectl=`curl -L -s https://dl.k8s.io/release/stable.txt` >> $GITHUB_OUTPUT
          echo helm=`curl --silent "https://api.github.com/repos/helm/helm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'` >> $GITHUB_OUTPUT
          echo codeserver=$(curl -s "https://api.github.com/repos/coder/code-server/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT
          echo ghcli=$(curl -s "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all    
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Log in to the Github Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Log in to the Gitlab Container registry
        uses: docker/login-action@v4
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_ACCOUNT }}
          password: ${{ secrets.GITLAB_TOKEN }} 

      - name: Build and Push images to GitHub
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.image }}
          push: true
          labels: org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            ${{ secrets.GITLAB_REGISTRY_PATH }}/${{ matrix.image }}:latest
            ${{ secrets.GITLAB_REGISTRY_PATH }}/${{ matrix.image }}:${{ steps.meta.outputs.tag }}
          platforms: linux/amd64
          build-args: |
            KUBECTL_VERSION=${{ steps.versions.outputs.kubectl }}
            HELM_VERSION=${{ steps.versions.outputs.helm }}
            CODESERVER_VERSION=${{ steps.versions.outputs.codeserver }}
            GHCLI_VERSION=${{ steps.versions.outputs.ghcli }}
          cache-from: type=gha
