name: Images for Kubernetes pods
on:
  pull_request:
    paths-ignore:
      - deploy/**
      - charts/**
  schedule:
    - cron: "0 2 * * 0"

jobs: 
  changed-images:
    if: github.event_name == 'pull_request'
    name: Get Changed Files for Testing
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.changed-files.outputs.all_changed_files }}
      kubectl: ${{ steps.outputs.versions.kubectl }}
      helm: ${{ steps.outputs.versions.helm }}
      codeserver: ${{ steps.outputs.versions.codeserver }}
      ghcli: ${{ steps.outputs.versions.ghcli }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          matrix: true
          files_ignore: |
            charts/**
            deploy/**
            .github/**

      - name: Get latest Runner Version and set repos
        id: versions
        run: |
          echo kubectl=`curl -L -s https://dl.k8s.io/release/stable.txt` >> $GITHUB_OUTPUT
          echo helm=`curl --silent "https://api.github.com/repos/helm/helm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'` >> $GITHUB_OUTPUT
          echo codeserver=$(curl -s "https://api.github.com/repos/coder/code-server/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT
          echo ghcli=$(curl -s "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-) >> $GITHUB_OUTPUT

  test-image:
    name: Build and Test Container Images
    if: github.event_name == 'pull_request'
    needs: changed-images
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.target }}
      cancel-in-progress: true    
    permissions:
      contents: read
      pull-requests: read
      packages: write
    strategy:
      matrix:
        target: ${{ fromJSON(needs.changed-images.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all    
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
         
      - name: Log in to the Github Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Test Build for ${{ matrix.target }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.target }}
          push: false
          sbom: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:test
          platforms: linux/amd64
          build-args: |
            KUBECTL_VERSION=${{ needs.changed-images.outputs.kubectl }}
            HELM_VERSION=${{ needs.changed-images.outputs.helm }}
            CODESERVER_VERSION=${{ needs.changed-images.outputs.codeserver }}
            TFSEC_VERSION=${{ needs.changed-images.outputs.tfsec }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:test'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
